/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Consulta;

import controlador.ControladorProductos;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Entidades.Productos;
import vista.IntFacturacion;
import vista.IntProductos;
import vista.frmInicio;

/**
 *
 * @author hypadilla
 */
public final class ConsultarProductos extends javax.swing.JInternalFrame {

    int Interfaz;
    IntFacturacion facturacion;

    /**
     * Creates new form ConsultarTerceros
     */
    public ConsultarProductos() {
        initComponents();
        LlenarTabla("");
        txtFiltro.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }
        });
        Interfaz = 0;
    }

    public ConsultarProductos(String Codigo, IntFacturacion facturacion) {
        initComponents();
        LlenarTabla("");
        txtFiltro.setText(Codigo);
        this.facturacion = facturacion;
        txtFiltro.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }
        });
        Interfaz = 1;
    }

    void LlenarTabla(String Consulta) {
        String col[] = {"ID", "CODIGO", "REFERENCIA", "DESCRIPCIÓN", "CANTIDAD", "VR VENTA"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tblConsulta.setModel(tableModel);

        tblConsulta.getColumnModel().getColumn(0).setMaxWidth(0);
        tblConsulta.getColumnModel().getColumn(0).setMinWidth(0);
        tblConsulta.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblConsulta.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        ControladorProductos controladorProductos = new ControladorProductos();
        ArrayList<Object> productos = controladorProductos.MostrarTodos(Consulta);
        for (Object item : productos) {
            Productos producto = (Productos) item;
            tableModel.addRow(new Object[]{producto.getId(), producto.getCodigo(), producto.getReferencia(), producto.getDescripcion(), producto.getCantidad(), (producto.getVentaNeto() * (1 + (producto.getPorcVentaIva() / 100)))});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consultar Productos");

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setText("FILTRAR POR CÓDIGO O NOMBRE");

        txtFiltro.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblConsultaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltro)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void tblConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultaMousePressed
        if (evt.getClickCount() > 1) {
            Point point = evt.getPoint();
            int row = tblConsulta.rowAtPoint(point);
            int column = tblConsulta.columnAtPoint(point);
            TableModel model = tblConsulta.getModel();

            switch (Interfaz) {
                case 0:
                    IntProductos t = new IntProductos(Integer.parseInt(model.getValueAt(row, 0).toString()));
                    frmInicio.jdpEscritorio.add(t);
                    t.show();
                    break;
                case 1:
                    facturacion.txtCodigoProducto.setText(model.getValueAt(row, 1).toString());
                    facturacion.txtCodigoProducto.requestFocus();
                    facturacion.txtCantidad.setText("1");
                    facturacion.txtCantidad.requestFocus();
                    break;
            }
            dispose();
        }
    }//GEN-LAST:event_tblConsultaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
