/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Consulta;

import controlador.ControladorUsuario;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Entidades.Usuarios;
import vista.IntUsuarios;
import vista.frmInicio;

/**
 *
 * @author hypadilla
 */
public class ConsultarUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarTerceros
     */
    public ConsultarUsuarios() {
        initComponents();
        LlenarTabla("");
        txtFiltro.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }
        });
    }
    
    

    void LlenarTabla(String Consulta) {
        String col[] = {"ID", "USUARIO", /*"CONTRASEÑA",*/ "CORREO", "PREGUNTA SECRETA", "RESPUESTA SECRETA", "ESTADO"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tblConsulta.setModel(tableModel);

        tblConsulta.getColumnModel().getColumn(0).setMaxWidth(0);
        tblConsulta.getColumnModel().getColumn(0).setMinWidth(0);
        tblConsulta.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblConsulta.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        ControladorUsuario controladorUsuario = new ControladorUsuario();
        ArrayList<Object> usuarios = controladorUsuario.MostrarTodos(Consulta);
        for (Object item : usuarios) {
            Usuarios usuario = (Usuarios) item;
            String estado;
            if (usuario.getEstado()){
                estado="ACTIVO";
            }else{
                estado="INACTIVO";
            }
            tableModel.addRow(new Object[]{usuario.getId(),usuario.getUsuario(), /*usuario.getClave(),*/ usuario.getCorreoElectronico(), usuario.getPregunta(), usuario.getRespuestaSecreta(), estado});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupEstado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        rBtnActivo = new javax.swing.JRadioButton();
        rBtnInactivo = new javax.swing.JRadioButton();
        rBtnCualquiera = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Consultar Usuarios");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/src/icono2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setText("FILTRAR POR CÓDIGO O NOMBRE");

        txtFiltro.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsulta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblConsultaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblConsulta);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setText("ESTADO:");

        btnGroupEstado.add(rBtnActivo);
        rBtnActivo.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        rBtnActivo.setText("ACTIVO");

        btnGroupEstado.add(rBtnInactivo);
        rBtnInactivo.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        rBtnInactivo.setText("INACTIVO");

        btnGroupEstado.add(rBtnCualquiera);
        rBtnCualquiera.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        rBtnCualquiera.setText("CUALQUIERA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltro)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rBtnActivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rBtnInactivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rBtnCualquiera)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rBtnActivo)
                    .addComponent(rBtnInactivo)
                    .addComponent(rBtnCualquiera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultaMousePressed
        if (evt.getClickCount() > 1) {
            Point point = evt.getPoint();
            int row = tblConsulta.rowAtPoint(point);
            int column = tblConsulta.columnAtPoint(point);
            TableModel model = tblConsulta.getModel();

            IntUsuarios t = new IntUsuarios(Integer.parseInt(model.getValueAt(row, 0).toString()));
            frmInicio.jdpEscritorio.add(t);
            t.show();
            
            dispose();
            //JOptionPane.showMessageDialog(this, );
        }
    }//GEN-LAST:event_tblConsultaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rBtnActivo;
    private javax.swing.JRadioButton rBtnCualquiera;
    private javax.swing.JRadioButton rBtnInactivo;
    private static javax.swing.JTable tblConsulta;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
