/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Consulta;

import controlador.ControladorTerceros;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Entidades.Terceros;
import vista.IntFacturacion;
import vista.frmInicio;
import vista.intTerceros;

/**
 *
 * @author hypadilla
 */
public final class ConsultarTerceros extends javax.swing.JInternalFrame {

    int Interfaz;
    IntFacturacion facturacion;

    /**
     * Creates new form ConsultarTerceros
     */
    public ConsultarTerceros() {
        initComponents();
        LlenarTabla("");
        txtFiltro.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }
        });
        Interfaz = 0;
    }

    public ConsultarTerceros(String text, IntFacturacion aThis) {
        initComponents();
        LlenarTabla("");
        txtFiltro.setText(text);
        this.facturacion = aThis;
        txtFiltro.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                LlenarTabla(txtFiltro.getText());
            }
        });
        Interfaz = 1;
    }

    void LlenarTabla(String Consulta) {
        String col[] = {"ID", "TIPO", "DOCUMENTO", "NOMBRE", "DIRECCIÓN", "CORREO", "TÉLEFONO"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tblConsulta.setModel(tableModel);

        tblConsulta.getColumnModel().getColumn(0).setMaxWidth(0);
        tblConsulta.getColumnModel().getColumn(0).setMinWidth(0);
        tblConsulta.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblConsulta.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        ControladorTerceros controladorTerceros = new ControladorTerceros();
        ArrayList<Object> terceros = controladorTerceros.MostrarTodos(Consulta);
        terceros.stream().map((item) -> (Terceros) item).forEach((tercero) -> {
            tableModel.addRow(new Object[]{tercero.getIdTerceros(), tercero.getTipoTercero(), tercero.getDocumento(), tercero.getNombre(), tercero.getDireccion(), tercero.getCorreo(), tercero.getTelefono()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consultar Terceros");

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setText("FILTRAR POR CÓDIGO O NOMBRE");

        txtFiltro.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsulta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblConsultaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltro)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultaMousePressed
        if (evt.getClickCount() > 1) {
            Point point = evt.getPoint();
            int row = tblConsulta.rowAtPoint(point);
            int column = tblConsulta.columnAtPoint(point);
            TableModel model = tblConsulta.getModel();

            switch (Interfaz) {
                case 0:
                    intTerceros t = new intTerceros(Integer.parseInt(model.getValueAt(row, 0).toString()));
                    frmInicio.jdpEscritorio.add(t);
                    t.show();
                    break;
                case 1:
                    facturacion.txtIdTercero.setText(model.getValueAt(row, 1).toString());
                    facturacion.txtIdTercero.requestFocus();
                    facturacion.txtCodigoProducto.requestFocus();
                    break;
            }

            dispose();
            //JOptionPane.showMessageDialog(this, );
        }
    }//GEN-LAST:event_tblConsultaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tblConsulta;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
