/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorConceptos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Entidades.Conceptos;

/**
 *
 * @author hypadilla
 */
public class IntConceptos extends javax.swing.JInternalFrame {

    int id;

    /**
     * Creates new form IntConceptos
     */
    public IntConceptos() {
        initComponents();
        id = 0;
    }

    public IntConceptos(int id) {
        initComponents();
        this.id = id;
        txtCodigo.setEnabled(false);
        ArrayList<String> Filtro = new ArrayList();
        Filtro.add("idConceptos");
        Filtro.add(String.valueOf(id));
        Filtro.add("Int");
        ControladorConceptos controladorConceptos = new ControladorConceptos();
        Conceptos conceptos = new Conceptos();
        conceptos = (Conceptos) controladorConceptos.Mostrar(Filtro);
        txtCodigo.setText(conceptos.getCodigo());
        txtEtiqueta.setText(conceptos.getEtiqueta());
        txtDescripcion.setText(conceptos.getDescripcion());
        if (conceptos.isManejaConsecutivo()) {
            checkManejaConsecutivo.setSelected(true);
        } else {
            checkManejaConsecutivo.setSelected(false);
        }
        txtPrefijo.setText(conceptos.getPrefijo());
        txtUltConsecutivo.setText(String.valueOf(conceptos.getUltimoConsecutivo()));
        txtResolucionDIAN.setText(conceptos.getResolucionDIAN());
        switch (conceptos.getNaturalezaDinero()) {
            case 1:
                rbCredito.setSelected(true);
                break;
            case 2:
                rbDebito.setSelected(true);
                break;
            case 3:
                rbNingunDinero.setSelected(true);
                break;
            default:
                break;
        }
        switch (conceptos.getNaturalezaInventario()) {
            case 1:
                rbEntrada.setSelected(true);
                break;
            case 2:
                rbSalida.setSelected(true);
                break;
            case 3:
                rbNingunInventario.setSelected(true);
                break;
            default:
                break;
        }

        this.setTitle("ACTUALIZANDO CONCEPTO");
        btnGuardar.setText("ACTUALIZAR");
        btnLimpiar.setText("NUEVO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbxNaturalezaDinero = new javax.swing.ButtonGroup();
        gbxNaturalezaInventario = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        rbCredito = new javax.swing.JRadioButton();
        rbDebito = new javax.swing.JRadioButton();
        txtEtiqueta = new javax.swing.JTextField();
        checkManejaConsecutivo = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        txtPrefijo = new javax.swing.JTextField();
        txtUltConsecutivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbNingunDinero = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rbEntrada = new javax.swing.JRadioButton();
        rbSalida = new javax.swing.JRadioButton();
        rbNingunInventario = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtResolucionDIAN = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("NUEVO CONCEPTO");
        setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setText("CÓDIGO");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setText("DESCRIPCIÓN");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel5.setText("NATURALEZA DEL DINERO");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel6.setText("ETIQUETA ");

        gbxNaturalezaDinero.add(rbCredito);
        rbCredito.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        rbCredito.setSelected(true);
        rbCredito.setText("CRÉDITO");

        gbxNaturalezaDinero.add(rbDebito);
        rbDebito.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        rbDebito.setText("DÉBITO");

        checkManejaConsecutivo.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        checkManejaConsecutivo.setText("¿MANEJA CONSECUTIVO?");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel3.setText("ÚLTIMO CONSECUTIVO");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setText("PREFIJO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUltConsecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUltConsecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gbxNaturalezaDinero.add(rbNingunDinero);
        rbNingunDinero.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        rbNingunDinero.setText("NINGUNA");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel7.setText("NATURALEZA DEL INVENTARIO");

        gbxNaturalezaInventario.add(rbEntrada);
        rbEntrada.setText("ENTRADA");

        gbxNaturalezaInventario.add(rbSalida);
        rbSalida.setText("SALIDA");

        gbxNaturalezaInventario.add(rbNingunInventario);
        rbNingunInventario.setText("NINGUNA");

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel8.setText("RESOLUCIÓN DIAN");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcion))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbCredito)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbDebito)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbNingunDinero))
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbEntrada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbSalida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbNingunInventario))
                                    .addComponent(jLabel5))
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEtiqueta)
                            .addComponent(jLabel6)
                            .addComponent(checkManejaConsecutivo)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtResolucionDIAN)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(checkManejaConsecutivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbCredito)
                            .addComponent(rbDebito)
                            .addComponent(rbNingunDinero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbEntrada)
                            .addComponent(rbSalida)
                            .addComponent(rbNingunInventario)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResolucionDIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Limpiar() {
        this.setTitle("NUEVO CONCEPTO");
        txtCodigo.setEnabled(true);
        txtCodigo.setText("");
        txtEtiqueta.setText("");
        txtDescripcion.setText("");
        txtPrefijo.setText("");
        txtUltConsecutivo.setText("");
        txtResolucionDIAN.setText("");
        checkManejaConsecutivo.setSelected(false);
        rbNingunDinero.setSelected(true);
        rbNingunInventario.setSelected(true);
        btnGuardar.setText("GUARDAR");
        btnLimpiar.setText("LIMPIAR");
        id = 0;

    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Conceptos var = new Conceptos();
        var.setId(id);
        var.setCodigo(txtCodigo.getText());
        var.setDescripcion(txtDescripcion.getText());
        var.setEtiqueta(txtEtiqueta.getText());
        if (rbCredito.isSelected()) {
            var.setNaturalezaDinero(1);
        } else if (rbDebito.isSelected()) {
            var.setNaturalezaDinero(2);
        } else if (rbNingunDinero.isSelected()) {
            var.setNaturalezaDinero(3);
        } else {
            JOptionPane.showMessageDialog(this, "Seleecione una naturaleza del dinero");
            return;
        }
        if (rbEntrada.isSelected()) {
            var.setNaturalezaInventario(1);
        } else if (rbSalida.isSelected()) {
            var.setNaturalezaInventario(2);
        } else if (rbNingunInventario.isSelected()) {
            var.setNaturalezaInventario(3);
        } else {
            JOptionPane.showMessageDialog(this, "Seleecione una naturaleza de inventario");
            return;
        }
        if (checkManejaConsecutivo.isSelected()) {
            var.setManejaConsecutivo(true);
        } else {
            var.setManejaConsecutivo(false);
        }

        var.setPrefijo(txtPrefijo.getText());
        var.setUltimoConsecutivo(Integer.parseInt(txtUltConsecutivo.getText()));
        var.setResolucionDIAN(txtResolucionDIAN.getText());

        ControladorConceptos controladorConceptos = new ControladorConceptos();

        Object[] object = new Object[2];

        if (id > 0) {
            object = (Object[]) controladorConceptos.Editar(var);
        } else {
            object = (Object[]) controladorConceptos.Insertar(var);
        }

        if (object[0] == "String") {
            JOptionPane.showMessageDialog(this, object[1]);
            return;
        }
        if (object[0] == "Boolean") {
            if (id > 0) {
                if (((boolean) object[1])) {
                    JOptionPane.showMessageDialog(this, "Actualización Exitoso");
                } else {
                    JOptionPane.showMessageDialog(this, "Actualización Fallido");
                }
                return;
            }

            if (((boolean) object[1])) {
                JOptionPane.showMessageDialog(this, "Registro Exitoso");
                Limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Registro Fallido");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox checkManejaConsecutivo;
    private javax.swing.ButtonGroup gbxNaturalezaDinero;
    private javax.swing.ButtonGroup gbxNaturalezaInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbDebito;
    private javax.swing.JRadioButton rbEntrada;
    private javax.swing.JRadioButton rbNingunDinero;
    private javax.swing.JRadioButton rbNingunInventario;
    private javax.swing.JRadioButton rbSalida;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEtiqueta;
    private javax.swing.JTextField txtPrefijo;
    private javax.swing.JTextField txtResolucionDIAN;
    private javax.swing.JTextField txtUltConsecutivo;
    // End of variables declaration//GEN-END:variables
}
